apiVersion: apps/v1
kind: Deployment
metadata:
  name: poll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poll
  template:
    metadata:
      labels:
        app: poll
    spec:
      nodeSelector:
        "kubernetes.io/os": windows
      containers:
      - name: poll
        image: pollappacr.azurecr.io/poll:latest
        ports:
        - containerPort: 8000
        env:
        - name: pollapp
          value: "poll"
  
---
apiVersion: v1
kind: Service
metadata:
  name: poll
spec:
  type: LoadBalancer
  ports:
  - port: 8000
  selector:
    app: poll