apiVersion: apps/v1
kind: Deployment
metadata:
  name: poll-help-center
spec:
  replicas: 3
  selector:
    matchLabels:
      app: poll-help-center
  template:
    metadata:
      labels:
        app: poll-help-center
    spec:
      nodeSelector:
        "kubernetes.io/os": windows
      containers:
      - name: poll-help-center
        image: pollappnew1234.azurecr.io/poll:latest
        ports:
        - containerPort: 80
        env:
        - name: APPNAME
          value: "poll-help-center"
        - name: CONNSTR_Poll
          valueFrom:
            secretKeyRef:
              name: akvsecretscertwin
              key: SECERT_POLL
        volumeMounts:
          - name: azure
            mountPath: /mnt/azure
          - name: secrets-store-inline
            mountPath: "/mnt/secrets-store"
            readOnly: true
        imagePullPolicy: Always
      volumes:
      - name: secrets-store-inline
        csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname-win"
      - name: azure
        persistentVolumeClaim:
            claimName: azurefile
  
---
apiVersion: v1
kind: Service
metadata:
  name: poll-help-center
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: poll-help-center